PORT: 8888
GUI_URL: http://localhost:8888/app/
URL_PATH: /app

# Get the following values from EkoSys 
EKOSYS_URL: http://localhost:8888

CLIENT_ID: 5d380c06abc348168ba62ec6   # aka product id
ISSUER: https://localhost/
JWKS_URI: https://localhost/.well-known/jwks.json
AUDIENCE: http://localhost:8888/
AUTH_DOMAIN: localhost
AUTH_SCOPE: 'read:all'
LOGIN_URL:  oidc/authorize
LOGOUT_URL: oidc/logout
CHANGE_PWD_URL: http://localhost:8888/index.html?layout=main
REGISTER_URL: http://localhost:8888/index.html?layout=product-nonav&id=5d380c06abc348168ba62ec6
PWD_RESET_URL: http://localhost:8888/index.html?layout=main

LOGIN_REDIRECT: http://localhost:8888/app/index.html
LOGOUT_REDIRECT: http://localhost:8888/app/index.html

# FAKE_LOGIN: demo
